<?php if( $this->pages ) :  // TAMBAH PAGE ?>
	
	<?php foreach( $this->pages as $page ) : ?>
		<li id="page_<?php echo $page->getId(); ?>">
			<?php echo $this->partial('partials/menu-ajax-row.phtml', $page ); ?>
		</li>
	<?php endforeach; ?>
	
<?php elseif( $this->links ) : // TAMBAH PAGE LINK ?>
	
	<li id="page_0">
		<?php echo $this->partial('partials/menu-ajax-row.phtml', $this->links ); ?>
	</li>
	
<?php endif; ?>