<?php 
$this->jQuery()// CDN
			   //->setUiVersion('1.8') //jQuery UI version, automatically 1.8 = 1.8.latest
			   //->addStylesheet('https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/smoothness/jquery-ui.css')//add the css
			   // LOCAL PATH
			   ->setUiLocalPath($this->baseUrl().'/js/jquery/jquery-ui-1.8.18.custom.min.js')// CDN: setUiVersion('1.8.18')
	           ->addStylesheet($this->baseUrl().'/css/jquery-ui/smoothness/jquery-ui-1.8.21.custom.css')
	           ->addJavascriptFile($this->baseUrl() . '/js/admin/widgets.js')
			   ->addJavascriptFile($this->baseUrl() . '/js/jquery/jquery.equalHeight.js')
			   ->addOnLoad("
					 $('.portlet-content').equalHeight();
					 $('.column').equalHeight();
					 
					 TheWidgets.ajaxurl = '".$this->baseUrl(false)."/admin/ajax/widget';
					 TheWidgets.init();
				");
?>

<header>
	<h2>Widgets</h2>
</header>

<?php 
// messages
echo $this->flashMessenger('success'); 
echo $this->flashMessenger('error'); 
?>

<?php if(count($this->widgets) > 0) : ?>

<div id="widgets">

	<!-- Available Widget -->
	<div id="widgets-left" class="portlet">
		<div class="portlet-header">
			<h3>Available Widgets
				<span id="removing-widget" style="display: none;">
					Deactivate
					<span></span>
				</span>
			</h3>
		</div>
		<div class="portlet-inside" style="display: block;">
			<div id="available-widget" class="widget-holder">	
				<div class="info">
					<?php echo $this->translate("Drag widgets from here to a sidebar on the right to activate them. 
					Drag widgets back here to deactivate them and delete their settings.") ?>
				</div>
				<?php 
				/* =================
				 * AVAILABLE SIDEBAR
				 * =================
				 */
				if( $this->availablewidgets ) : ?>
					<?php 
					/**
					 * looping available sidebar
					 */
					foreach($this->availablewidgets as $widget) : 
						/**
						 * variabel count : jumlah widget value + 1
						 * untuk multi widget
						 * set value $count pada input tipe hidden class multi
						 */
						$count = count($widget['data']) + 1; ?>
						<!-- widget -->
						<div id="widget_<?php echo $widget['id']; ?>" class="portlet">
							<div class="portlet-header">
								<h4><?php echo $widget['title']; ?></h4>
								<span class="widget-name"></span>
							</div>
							<div class="portlet-content"><?php echo $widget['description']; ?></div>
							<div class="portlet-inside">
								<div class="portlet-form">
									<form action="#">
									<ul>
										<li>
											<label for="title_<?php echo $widget['name']; ?>">Title : </label>
											<input type="text" name="title" value="" />
										</li>
										<!-- jika widget count aktif -->
										<?php if( $widget['use_count'] ) : ?>
										<li>
											<label for="count_<?php echo $widget['name']; ?>" class="smalllabel">Number of <?php echo $widget['title']; ?> to show : </label>
											<input class="count" type="text" name="count" value="5" />
										</li>
										<?php endif; ?>
										<!-- /count -->
										<!-- jika widget page aktif -->
										<?php if( $widget['use_page'] && $this->pages ) : ?>
										<li>
											<label for="count_<?php echo $widget['name']; ?>">Page :</label>
											<select name="page">
											<?php foreach( $this->pages as $page ) : ?>
												<option value="<?php echo $page->getId() ?>"><?php echo $page->content_name ?></option>
											<?php endforeach; ?>
											</select>
										</li>
										<?php endif; ?>
										<!-- /page -->
										<!-- jika widget menu aktif -->
										<?php if( $widget['use_menu'] && $this->menus ) : ?>
										<li>
											<label for="menu_<?php echo $widget['name']; ?>">Menu :</label>
											<select name="menu">
											<?php foreach( $this->menus as $key => $menu ) : ?>
												<option value="<?php echo $key ?>"><?php echo $menu['name'] ?></option>
											<?php endforeach; ?>
											</select>
										</li>
										<?php endif; ?>
										<!-- /menu -->
										<li id="widget-control">
											<div class="alignleft">
												<a class="widget-control-remove" href="#remove">Delete</a>|
												<a class="widget-control-close" href="#close">Close</a>
											</div>
											<div class="alignright">
												<img class="ajax-loader-widget" src="<?php echo $this->baseUrl() ?>/images/ajax_spin.gif"/>
												<input type="submit" class="widget-control-save ui-button ui-widget ui-state-default ui-corner-all" value="Save" />
											</div>
										</li>
									</ul>
									<!-- [IMPORTANT] multi widget, set value count widget value -->
									<input type="hidden" class="multi" name="multi" value="<?php echo $count; ?>" />
									<!-- [IMPORTANT] add widget, input hidden class add value TRUE -->
									<input type="hidden" class="add" name="add" value="true" />
									</form>
								</div>
								<div class="clear"></div>
							</div>
						</div>
						<!-- /widget -->
					<?php endforeach; ?>
				<?php endif; ?>
			</div> <!-- /available widget -->
		</div>	
	</div>	

	<!-- Register Widget -->
	<div id="widgets-right">
		
		<?php foreach( $this->widgets as $widget_title => $widget_data ) : ?>
			<div class="widget-holder-wrap portlet">
				<div class="portlet-header">
					<h3>
						<?php 
						// buat title header
						list( $w, $n ) = explode('_', $widget_title, 2);
						$title = str_replace('_', ' ', $n);
						echo ucwords($title); 						
						?>
						<span>
							<img class="ajax-loader-widget" src="<?php echo $this->baseUrl() ?>/images/ajax_spin.gif"/>
						</span>
					</h3>
				</div>
				<div class="portlet-inside" style="display: block;">
					<div id="<?php echo $widget_title ?>" class="widgets-sortables">
					<?php 
					foreach( $widget_data as $widget ) 
					{
						/**
						 * pisahkan value "-" : [nama_widget]-[posisi_widget]
						 * partial widget : [nama_widget] sbg ARRAY KEY dari widgets
						 * partial pos : [posisi_widget]
						 */
						list($widget_name, $widget_position) = explode('-', $widget);
						echo $this->partial('partials/widget-row.phtml', array(
								'widget' => $this->availablewidgets[$widget_name],
								'widget_position' => $widget_position,
								'pages' => $this->pages,
								'menus' => $this->menus
							)
						);
					} 
					?>
					</div>
				</div>	
			</div>	
		<?php endforeach; ?>
		
	</div>	
	
</div>	
	
<?php endif; ?>

