<tr>
	<td class="tleft" style="padding-left:50px;">
		<?php if($this->parent): ?>
			<b><?php echo strtoupper($this->data['content_name']); ?></b>
		<?php else : ?>
			&rarr;&nbsp;<?php echo ucwords($this->data['content_name']); ?>
		<?php endif; ?>
	</td>
	<td><?php echo ($this->data['content_status'] == 'L') ? 'Published' : 'Draft' ; ?></td>
	<td><?php echo $this -> getDate($this->data['content_date']); ?></td>
	<td>
	<ul class="actions">
		<li>
			<a class="view open-modal" href="#page-<?php echo $this->data['content_id']; ?>">view</a>
		</li>
		<li>
			<a class="edit" href="<?php echo $this->url( array( 'action' => 'edit', 'id' =>  $this->data['content_id']))  ?>"
			title="Edit <?php echo $this->data['content_name'] ?>" rel="tooltip">edit</a>
		</li>
		<li>
			<a class="delete" onclick="if ( !confirm('Are you sure ?') ) { return false; }"
			href="<?php echo $this->url( array( 'action' => 'delete', 'id' =>  $this->data['content_id']))  ?>"
			title="Delete <?php echo $this->data['content_name'] ?>" rel="tooltip">delete</a>
		</li>
	</ul></td>
</tr>
<!-- Modal Detail -->
<article id="page-<?php echo $this -> data['content_id']; ?>" class="hide full-block nested">
	<div class="article-container">

		<header>
			<h2><?php echo ucwords($this -> data['content_name']); ?></h2>
		</header>

		<section>
			<h5><?php echo $this -> getDate($this -> data['content_date']); ?></h5>
			<?php echo $this -> data['content_description']; ?>
			<?php if($this->data['content_image']) : ?>
			<!-- Image Minimenu Actions -->
			<div class="image-frame right">
				<img src="<?php echo $this->view->baseUrl() ?>/uploads/thumbnail/<?php echo $this->data['content_image'] ?>" alt="<?php echo ucwords($this -> data['content_name']); ?>">
				<ul class="image-actions">
					<li class="view">
						<a href="<?php echo $this->url( array( 'action' => 'edit', 'id' =>  $this->data['content_id']))  ?>">Edit</a>
					</li>
					<li class="delete">
						<a href="<?php echo $this->url( array( 'action' => 'delete', 'id' =>  $this->data['content_id']))  ?>"
						onclick="if ( !confirm('Are you sure ?') ) { return false; }">Delete</a>
					</li>
				</ul>
			</div>
			<?php endif; ?>
			<!-- /Image Minimenu Actions -->
		</section>
	</div>
</article>
<!-- /Modal Detail -->