<?php 
// parsing date
$date = new Zend_Date( $this->date );
$theDate = $date->get( Zend_Date::DATE_FULL );
?>
<tr>
	<td><input type="checkbox"></td>
	<td class="tleft"><?php echo ucwords($this->name); ?></td>
	<td><?php echo $this->getExcerpt( $this->description, 10, '[..]' ); ?></td>
	<td><?php echo $theDate; ?></td>
	<td>
		<ul class="actions">
			<li>
				<a class="view open-modal" href="#page-<?php echo $this->id; ?>">view</a>
			</li>
			<li>
				<a class="edit" href="<?php echo $this->url( array( 'action' => 'edit', 'id' =>  $this->id))  ?>" title="Edit <?php echo $this->name ?>" rel="tooltip">edit</a>
			</li>
			<li>
				<a class="delete" onclick="if ( !confirm('Are you sure ?') ) { return false; }"
				href="<?php echo $this->url( array( 'action' => 'delete', 'id' =>  $this->id))  ?>" title="Delete <?php echo $this->name ?>" rel="tooltip">delete</a>
			</li>
		</ul>
	</td>
</tr>

<!-- Modal Detail -->
<article id="page-<?php echo $this->id; ?>" class="hide full-block nested">
	<div class="article-container">

		<header>
			<h2><?php echo ucwords($this->name); ?></h2>
		</header>

		<section>
			<h5><?php echo $theDate; ?></h5>
			<?php echo $this->description; ?>
			<?php if($this->image) : ?>
			<!-- Image Minimenu Actions -->
			<div class="image-frame right">
				<img src="<?php echo $this->view->baseUrl() ?>/uploads/thumbnail/<?php echo $this->image ?>" alt="<?php echo ucwords($this->name); ?>">
				<ul class="image-actions">
					<li class="view">
						<a href="<?php echo $this->url( array( 'action' => 'edit', 'id' =>  $this->id))  ?>">Edit</a>
					</li>
					<li class="delete">
						<a href="<?php echo $this->url( array( 'action' => 'delete', 'id' =>  $this->id))  ?>" 
							onclick="if ( !confirm('Are you sure ?') ) { return false; }">Delete</a>
					</li>
				</ul>
			</div>
			<?php endif; ?>
			<!-- /Image Minimenu Actions -->
		</section>
	</div>
</article>
<!-- /Modal Detail -->
		